[platformio]
src_dir = main
default_envs = esp32-c6

[env]
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_build.extra_flags = -DCONFIG_LITTLEFS_FOR_IDF_3_2
build_flags =
    '-DWIFI_SSID="${sysenv.WIFI_SSID}"'
    '-DWIFI_PASS="${sysenv.WIFI_PASS}"'
    '-DCF_TUNNEL_TOKEN="${sysenv.CF_TUNNEL_TOKEN}"'
    '-DCF_HOSTNAME="${sysenv.CF_HOSTNAME}"'
    '-DCF_CONNECTOR_ID="${sysenv.CF_CONNECTOR_ID}"'

; ---- Boards ----
[env:esp32]
platform = espressif32
board = esp32dev
board_build.flash_mode = dio

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.flash_mode = dio

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
board_build.flash_mode = dio

[env:esp32-c6]
platform = espressif32
board = esp32-c6-devkitc-1
board_build.flash_mode = dio
board_upload.flash_size = 4MB
